---
kind: role
version: v2
metadata:
  name: admin-prod
  namespace: default
spec:
  logins: [ admin ]
  max_session_ttl: 90h0m0s
  namespaces: ['*']
  node_labels:
    'environment': 'prod'
  resources:
    '*': [read, write]
