---
- name: Reboot Server
  shell: "sleep 2 && shutdown -r now"
  async: 1
  poll: 0
  ignore_errors: true

- name: Wait for the server to come back from the dead
  local_action:
    module: wait_for
      host={{ansible_host}}
      port=22
      state=started
      delay=10
      timeout=300
